# Permalinks
permalink:           pretty

# Setup
title:               Progress
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
url:                 http://alexanderussell.github.io
baseurl:             /progress-for-jekyll
analytics_id:

# Owner/author information
owner:
  name:           Alex Russell
  avatar:         avatar.png
  bio:            "Designer."
  email:          alex@collectivelymade.com
  twitter:        alexanderussell
  github:         alexanderussell
  instagram:      alexanderussell
  dribbble:       alexanderussell
  location:       "Lincoln, NE"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
